version: '3.8'

services:
  web:
    build:
      context: ./web
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql://root:example@db/mydb
    volumes:
      - ./web:/app

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydb
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
